{
 "title": "account_alerts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Alerts Generated",
   "type": "table",
   "description": "account_alerts",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT type , account, details, created_date, status from account_alerts"
    }
   ]
  },
  {
   "title": "Messages in Transactions Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"input\"}[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in Activities Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"input_webtxn\"}[5m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages in Alerts Topic",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"alert_accounts\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}